### PR TITLE
Hello, these corrections were detected in 84000 editorial process. I …

### PR DESCRIPTION
**Pull request by Celso-Scott**
…checked everything in the scans using the HTML script found on the old github/derge-kangyur repository. I have made a few improvements to this HTML script so that it also includes W3CN20612, which has a very clear print; and also I adjusted the scans for W4CZ5369 to align just a bit better. If you think it would be useful here is my version of the updated HTML script:

https://drive.google.com/file/d/1TB44naRbVEAOHdNLpQpqV0PV1na0eFqS/view?usp=sharing

For any questions you can reach me at celso.wilkinson@84000.co
Thank you and best wishes,
Celso

### CODE REVIEW

**Comment by eroux** [comment]
ah, interesting approach! Maybe let's wait for the resolution of https://github.com/buda-base/library-issues/issues/299#issuecomment-706529845 before we merge that, as it will probably solve the volume alignment... For page alignment we took a more detailed approach and have some per-volume pagination correspondences here:

https://github.com/brunogml/rKTs/tree/master/paginations

I'm in the process of importing that in BDRC but we won't change the file names, just the display on the website so it won't really impact this script. Something that could be done is to use these files though, the js script could download them on github or something like that... wdyt?

**Comment by Celso-Scott** [comment]
Ha, that's a funny coincidence that you were discussing the volumes in W3CN20612 probably around the same time I was editing that HTML script. By the way, just to clarify, this pull request doesn't include the HTML script it just has some corrections we found in the Dege text input. I hope making a pull request like this is the best avenue for suggesting out these corrections.

Thanks for pointing out these pagination files, so does that align the pages for all of those Kangyur/Tengyur editions? That sounds really useful! I don't think I know enough to write that into a script though, I'm a bit of a newbie and I was just barely able to figure out how that HTML script worked, but I'll investigate it and see if I can figure it out. It all looks very inspiring. Thanks for your reply here!

**Comment by eroux** [comment]
We have the pagination files for the main canonical editions yes.

Oh right, I was confused about this pull request, of course let's merge it

**Comment by Celso-Scott** [comment]
Hi Elie, I just wanted to follow up on this pull request since it has been a few months since I had made the request. Were there any issues with these corrections? As I mentioned in the initial commit, these changes are spelling corrections to the input that were detected in the 84000 editorial process. If there are any protocols or documentation you would like me to follow for making these corrections please let me know, but generally I've been trying to be quite meticulous and checking all the corrections against the scans of the Degé W4CZ5369, W30532, W3CN20612, and W22084. The reason I've been a bit eager to merge these corrections is so that I can workout with Dominique the migration back downstream to the 84000 database, so that the corrections are maintained in the source upstream. I believe originally we were pulling the eKangyur from github.com/Esukhia/derge-kangyur, but as that has been archived, I assumed that this would be the place to report corrections.

**Comment by eroux** [comment]
Hi! I don't think there's any problem with the pull request, it's more of a workflow problem on our end... @ngawangtrinley can we define / document a workflow for that kind of cases?

**Comment by Celso-Scott** [comment]
Thanks Elie! Yes, @ngawangtrinley  when you get a chance please let me know what method for reporting these corrections is most convenient for you, I'm happy to adjust my workflow as is needed.

**Comment by ngawangtrinley** [comment]
Hi there! Sorry for the (twice) late reply. Tenzin is going to add a few commands to the CLI of the OpenPecha toolkit so you'll be able to directly update the opf on the master branch. We'll merge the current updates on our side tomorrow and will send you a short tutorial shortly after that.  
  
Happy new year to you and all the team!

**Comment by 10zinten** [comment]
Hi @Celso-Scott, sorry for the delay. Here are the commands needed to run for this PR to merge.

First install openpecha toolkit
  ```
  pip install openpecha
  ```

Then run this command
```
openpecha update-layers <pecha-number> <pecha_path>
```
here for `P000001`, the `pecha-number` is `1`.

**Comment by Celso-Scott** [comment]
Thank you NT and Tenzin. So I have installed the openpecha toolkit. Should I be running this 'update-layers' command now? or should I wait until you create an 84000 branch? 

Sorry, I'm not familiar with the form of this toolkit, is the <pecha_path> meant to point to the cloned repository on my local computer? I attempted the command `openpecha update-layers 1 C:\Users\ohoah\Desktop\GIT_Repos\P000001` (this was the cloned repo on my desktop), but this didn't seem to work.

**Comment by 10zinten** [comment]
Yes, u can just run the command as of now. We are planing to setup the branch later. 

Can u copy past the error in here?

**Comment by Celso-Scott** [comment]
Hi Tenzin, here is the error I got:

C:\Users\ohoah>openpecha update-layers 1 C:\Users\ohoah\Desktop\GIT_Repos\P000001
Traceback (most recent call last):
  File "c:\users\ohoah\appdata\local\programs\python\python38\lib\site-packages\git\__init__.py", line 83, in <module>
    refresh()
  File "c:\users\ohoah\appdata\local\programs\python\python38\lib\site-packages\git\__init__.py", line 73, in refresh
    if not Git.refresh(path=path):
  File "c:\users\ohoah\appdata\local\programs\python\python38\lib\site-packages\git\cmd.py", line 278, in refresh
    raise ImportError(err)
ImportError: Bad git executable.
The git executable must be specified in one of the following ways:
    - be included in your $PATH
    - be set via $GIT_PYTHON_GIT_EXECUTABLE
    - explicitly set via git.refresh()

All git commands will error until this is rectified.

This initial warning can be silenced or aggravated in the future by setting the
$GIT_PYTHON_REFRESH environment variable. Use one of the following values:
    - quiet|q|silence|s|none|n|0: for no warning or exception
    - warn|w|warning|1: for a printed warning
    - error|e|raise|r|2: for a raised exception

Example:
    export GIT_PYTHON_REFRESH=quiet


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\ohoah\appdata\local\programs\python\python38\lib\runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\ohoah\appdata\local\programs\python\python38\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\ohoah\AppData\Local\Programs\Python\Python38\Scripts\openpecha.exe\__main__.py", line 5, in <module>
  File "c:\users\ohoah\appdata\local\programs\python\python38\lib\site-packages\openpecha\cli.py", line 5, in <module>
    from git import Repo
  File "c:\users\ohoah\appdata\local\programs\python\python38\lib\site-packages\git\__init__.py", line 85, in <module>
    raise ImportError('Failed to initialize: {0}'.format(exc))
ImportError: Failed to initialize: Bad git executable.
The git executable must be specified in one of the following ways:
    - be included in your $PATH
    - be set via $GIT_PYTHON_GIT_EXECUTABLE
    - explicitly set via git.refresh()

All git commands will error until this is rectified.

This initial warning can be silenced or aggravated in the future by setting the
$GIT_PYTHON_REFRESH environment variable. Use one of the following values:
    - quiet|q|silence|s|none|n|0: for no warning or exception
    - warn|w|warning|1: for a printed warning
    - error|e|raise|r|2: for a raised exception

Example:
    export GIT_PYTHON_REFRESH=quiet

**Comment by 10zinten** [comment]
Hi @Celso-Scott, looks like you haven't properly install the git. Follow this https://stackoverflow.com/a/51038428/5757501 to resolve the issue.

After that, please update openpecha-toolkit before updating the pecha. We have patched some bug fixes. Run this command to update the openpecha-toolkit.
```
pip install --upgrade openpecha
```

**Comment by Celso-Scott** [comment]
Thank you @10zinten, I have believe I have git installed now (sorry about that, I thought I had it installed, but it wasn't and I had initially been cloning the repository through sublime merge).

I updated openpecha and then ran the update-layers command again from my terminal. This time it said:

`C:\Users\ohoah>openpecha update-layers 1 C:\Users\ohoah\Desktop\GIT_Repos\P000001
[INFO] Downloading P000001 ...
C:\Users\ohoah\.openpecha\data\P000001
[INFO] Updating P000001 ...
Traceback (most recent call last):
  File "c:\users\ohoah\appdata\local\programs\python\python38\lib\runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\ohoah\appdata\local\programs\python\python38\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\ohoah\AppData\Local\Programs\Python\Python38\Scripts\openpecha.exe\__main__.py", line 7, in <module>
  File "c:\users\ohoah\appdata\local\programs\python\python38\lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "c:\users\ohoah\appdata\local\programs\python\python38\lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "c:\users\ohoah\appdata\local\programs\python\python38\lib\site-packages\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\users\ohoah\appdata\local\programs\python\python38\lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\ohoah\appdata\local\programs\python\python38\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "c:\users\ohoah\appdata\local\programs\python\python38\lib\site-packages\openpecha\cli.py", line 353, in update_layers
    pecha.update()
  File "c:\users\ohoah\appdata\local\programs\python\python38\lib\site-packages\openpecha\blupdate.py", line 272, in update
    self.update_vol(vol_fn.stem)
  File "c:\users\ohoah\appdata\local\programs\python\python38\lib\site-packages\openpecha\blupdate.py", line 244, in update_vol
    src_base = (self.src_opf_path / "base" / f"{vol_id}.txt").read_text()
  File "c:\users\ohoah\appdata\local\programs\python\python38\lib\pathlib.py", line 1230, in read_text
    return f.read()
  File "c:\users\ohoah\appdata\local\programs\python\python38\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x8d in position 8: character maps to <undefined>`

Did this work properly? It did mention this UnicodeDecodeError at the end, is this a problem? Thank you for your help and patience with me.

**Comment by 10zinten** [comment]
@Celso-Scott  sorry, we forgot to specify the `utf-8` encoding when reading text. In your case (Window), is using the system's default encoding when no encoding is specified. Anyway, it's being fixed.

Don't forget to upgrade openpecha-toolkit before you run the update command.

**Comment by Celso-Scott** [comment]
Thank you @10zinten. So did you want me to run the update again or should I wait for now?

**Comment by 10zinten** [comment]
@Celso-Scott yes, run the update command again

**Comment by Celso-Scott** [comment]
hi @10zinten, I updated openpecha to 0.6.30 and ran the update-layers again. I'm not sure if it worked, there was one error message at the end of the result:

C:\Users\ohoah>openpecha update-layers 1 C:\Users\ohoah\Desktop\GIT_Repos\P000001
[INFO] Updating P000001 ...
[INFO] Updating base of P000001 ...
Traceback (most recent call last):
  File "c:\users\ohoah\appdata\local\programs\python\python38\lib\runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\ohoah\appdata\local\programs\python\python38\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\ohoah\AppData\Local\Programs\Python\Python38\Scripts\openpecha.exe\__main__.py", line 7, in <module>
  File "c:\users\ohoah\appdata\local\programs\python\python38\lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "c:\users\ohoah\appdata\local\programs\python\python38\lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "c:\users\ohoah\appdata\local\programs\python\python38\lib\site-packages\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\users\ohoah\appdata\local\programs\python\python38\lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\ohoah\appdata\local\programs\python\python38\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "c:\users\ohoah\appdata\local\programs\python\python38\lib\site-packages\openpecha\cli.py", line 360, in update_layers
    pecha.update()
  File "c:\users\ohoah\appdata\local\programs\python\python38\lib\site-packages\openpecha\blupdate.py", line 276, in update
    self.update_vol(vol_fn.stem)
  File "c:\users\ohoah\appdata\local\programs\python\python38\lib\site-packages\openpecha\blupdate.py", line 250, in update_vol
    self.update_layers(
  File "c:\users\ohoah\appdata\local\programs\python\python38\lib\site-packages\openpecha\blupdate.py", line 244, in update_layers
    self.update_layer(layer, updater)
  File "c:\users\ohoah\appdata\local\programs\python\python38\lib\site-packages\openpecha\blupdate.py", line 235, in update_layer
    for _, ann in layer["annotations"].items():
AttributeError: 'list' object has no attribute 'items'

Is this attrubute error at the end an issue? I haven't updated python in a while, so if you think that may be an issue let me know. Thanks again

**Comment by 10zinten** [comment]
@Celso-Scott, we have just fixed that. 

Can you please update the toolkit and run the update command again?

**Comment by Celso-Scott** [comment]
@10zinten, yes I have updated to 0.6.31 and ran the update-layers command again. This time there appears to be a unicode error:

C:\Users\ohoah>openpecha update-layers 1 C:\Users\ohoah\Desktop\GIT_Repos\P000001
[INFO] Updating P000001 ...
[INFO] Updating base of P000001 ...
Traceback (most recent call last):
  File "c:\users\ohoah\appdata\local\programs\python\python38\lib\runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\ohoah\appdata\local\programs\python\python38\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\ohoah\AppData\Local\Programs\Python\Python38\Scripts\openpecha.exe\__main__.py", line 7, in <module>
  File "c:\users\ohoah\appdata\local\programs\python\python38\lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "c:\users\ohoah\appdata\local\programs\python\python38\lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "c:\users\ohoah\appdata\local\programs\python\python38\lib\site-packages\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\users\ohoah\appdata\local\programs\python\python38\lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\ohoah\appdata\local\programs\python\python38\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "c:\users\ohoah\appdata\local\programs\python\python38\lib\site-packages\openpecha\cli.py", line 360, in update_layers
    pecha.update()
  File "c:\users\ohoah\appdata\local\programs\python\python38\lib\site-packages\openpecha\blupdate.py", line 276, in update
    self.update_vol(vol_fn.stem)
  File "c:\users\ohoah\appdata\local\programs\python\python38\lib\site-packages\openpecha\blupdate.py", line 250, in update_vol
    self.update_layers(
  File "c:\users\ohoah\appdata\local\programs\python\python38\lib\site-packages\openpecha\blupdate.py", line 245, in update_layers
    self.dump(layer, layer_fn)
  File "c:\users\ohoah\appdata\local\programs\python\python38\lib\site-packages\openpecha\blupdate.py", line 204, in dump
    yaml.dump(
  File "c:\users\ohoah\appdata\local\programs\python\python38\lib\site-packages\yaml\__init__.py", line 290, in dump
    return dump_all([data], stream, Dumper=Dumper, **kwds)
  File "c:\users\ohoah\appdata\local\programs\python\python38\lib\site-packages\yaml\__init__.py", line 278, in dump_all
    dumper.represent(data)
  File "c:\users\ohoah\appdata\local\programs\python\python38\lib\site-packages\yaml\representer.py", line 28, in represent
    self.serialize(node)
  File "c:\users\ohoah\appdata\local\programs\python\python38\lib\site-packages\yaml\serializer.py", line 54, in serialize
    self.serialize_node(node, None, None)
  File "c:\users\ohoah\appdata\local\programs\python\python38\lib\site-packages\yaml\serializer.py", line 108, in serialize_node
    self.serialize_node(value, node, key)
  File "c:\users\ohoah\appdata\local\programs\python\python38\lib\site-packages\yaml\serializer.py", line 98, in serialize_node
    self.serialize_node(item, node, index)
  File "c:\users\ohoah\appdata\local\programs\python\python38\lib\site-packages\yaml\serializer.py", line 108, in serialize_node
    self.serialize_node(value, node, key)
  File "c:\users\ohoah\appdata\local\programs\python\python38\lib\site-packages\yaml\serializer.py", line 89, in serialize_node
    self.emit(ScalarEvent(alias, node.tag, implicit, node.value,
  File "c:\users\ohoah\appdata\local\programs\python\python38\lib\site-packages\yaml\emitter.py", line 115, in emit
    self.state()
  File "c:\users\ohoah\appdata\local\programs\python\python38\lib\site-packages\yaml\emitter.py", line 412, in expect_block_mapping_simple_value
    self.expect_node(mapping=True)
  File "c:\users\ohoah\appdata\local\programs\python\python38\lib\site-packages\yaml\emitter.py", line 244, in expect_node
    self.expect_scalar()
  File "c:\users\ohoah\appdata\local\programs\python\python38\lib\site-packages\yaml\emitter.py", line 268, in expect_scalar
    self.process_scalar()
  File "c:\users\ohoah\appdata\local\programs\python\python38\lib\site-packages\yaml\emitter.py", line 533, in process_scalar
    self.write_plain(self.analysis.scalar, split)
  File "c:\users\ohoah\appdata\local\programs\python\python38\lib\site-packages\yaml\emitter.py", line 1132, in write_plain
    self.stream.write(data)
  File "c:\users\ohoah\appdata\local\programs\python\python38\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode characters in position 0-5: character maps to <undefined>

**Comment by 10zinten** [comment]
Hi @Celso-Scott, the issue was Window specific issue. I was able to update the base on my computer. You can check it out on this [branch](https://github.com/OpenPecha/P000001/tree/base-update-review). This will soon be merged to the master branch.

**Comment by Celso-Scott** [comment]
Thank you @10zinten! The new branch looks good. Thank you for your help. If it is alright, at some point after you have the branches set up, I'd like to reach out to you again about migrating the openpecha branch to 84000's database. I think we are still currently getting our source from the archived database at Esukhia/derge-kangyur. But I'll bring our technician, Dom Latham, into the conversation who has a much better grasp of the code than I do.

**Comment by 10zinten** [comment]
@Celso-Scott sure, we will let you know when proper branch is setup.

**Pull request merged**
